### ISSUE TITLE
Way to set port when using alt.data_transformers.enable('data_server')

### ISSUE THREAD

**Issue by donovanr** [altair-viz/altair_data_server#10]
e.g. `alt.data_transformers.enable('data_server', port=12345)`.

I'm trying to use the data_server when sshing into my compute machine, and using `'data_server_proxied'` isn't working, perhaps related https://github.com/altair-viz/altair_data_server/issues/8 since I'm in a subdirectory.

I can pull the port out by looking at `print(chart.to_json())` and then ssh in again and forwarding that port, but since the port seems to be pretty random, that's less than ideal.

Any advice?

**Comment by jakevdp** [comment]
No, there's not any way to set the port currently, but that would be a useful enhancement.

**Comment by jakevdp** [comment]
As of version 0.4, controlling the port will be possible using:
```
alt.data_transformers.enable('data_server', port=1234)
```

**Comment by donovanr** [comment]
thanks!
