### ISSUE TITLE
Heroku alt.data_transformers.enable('data_server')

### ISSUE THREAD

**Issue by andrealee011** [altair-viz/altair_data_server#11]
Hi Jake,

I'm trying to enable data_server when deploying a dash app on Heroku. However, the plots are showing up blank. The app runs locally and requirements.txt includes all necessary packages.

I am getting the following error message: `Failed to load resource: net::ERR_CONNECTION_REFUSED`

Any advice?

**Comment by jakevdp** [comment]
You'll need to figure out how to serve the data as part of your heroku app rather than via localhost. I don't think altair_data_server will work for this use case - but you may be able to use a similar approach to create a heroku data server transformer.

**Comment by christopheralex** [comment]
Any possible solution ? Stuck on the same issue.

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
