### ISSUE TITLE
Blank chart displayed when `data_server` enabled in docker

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair_data_server#17]
Hi,
I'm having trouble to properly display charts on jupyter notebook when it is served from a docker container. The chart can display correctly with "json" `data_transformer` enabled, but not with "data_server" `data_transformer` enabled. Below is a screenshot:
![Screen Shot 2019-11-13 at 9 37 58 PM](https://user-images.githubusercontent.com/10766549/68829559-fcba1480-065d-11ea-93b1-169e4b2eb61d.png)
- the adblocker is disabled on my Chrome
- the javascript console shows 
![Screen Shot 2019-11-13 at 9 40 37 PM](https://user-images.githubusercontent.com/10766549/68829662-46a2fa80-065e-11ea-9f17-d919d3012a36.png)
- my `Dockerfile` looks like this
```Dockerfile
FROM python:3.7.4-slim

WORKDIR /app

COPY ./requirement.txt /app/

RUN pip --no-cache-dir install -r requirement.txt

EXPOSE 8888

VOLUME /app
```
Does this mean the "data_server" connection is somehow blocked in the container? How to correct this situation?

**Comment by deepcoder** [comment]
Hi, I am seeing this same problem with trying to use 'alt.data_transformers.enable('data_server')'.

I am using the 'official' docker image from Jupyter folks : https://hub.docker.com/u/jupyter
Jupyter Notebook Data Science Stack build on May 4, 2020.

If I understand the above discussion, either both the altair_data_server and jupyter-server-proxy or just the jupyter-server-proxy need to be pip baked into the docker image. Correct? 

If this is correct, what are correct steps recommended to do this? 

I would rather not have to learn how to do this myself. So I would like to get the correct info and request it to be done by the owner of the docker images at Jupyter. Perhaps they will install Altair within the Juypter environment as well :-) 

Thank you for your help and great work on Altair!
-- Dave

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
