### ISSUE TITLE
Make data server work with Binder?

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair_data_server#3]
This data server approach doesn't work with binder, because the localhost server is started on the backend, and so requests from the frontend cannot access it.

Is there any existing mechanism within binder to support port forwarding for background servers? I'm curious if this has come up in other contexts (cc/ @choldgraf)

**Comment by yuvipanda** [comment]
I do <3 Altair :)

`jupyter-server-proxy` is probably the right way to do this. Is there a way to specify:

1. The port the server should listen on
2. The url prefix the frontend JS should try to contact the server on

if these exist, I can whip up a jupyter-server-proxy config (https://jupyter-server-proxy.readthedocs.io/en/latest/) that'll help this work on JupyterHub and Binder.

Did I mention I really like Altair? :)

**Comment by jakevdp** [comment]
Awesome... so the way it's structured right now is that the port is chosen by portpicker, and stored at ``altair_data_server.data_server._provider.port``.

We could make the URL prefix for the frontend any reasonable value, as long as we return it correctly here: https://github.com/altair-viz/altair_data_server/blob/a393c5abcd3563d337163119c4c694cf83545658/altair_data_server/_altair_server.py#L45

**Comment by yuvipanda** [comment]
Sounds good! If someone gets around to doing the configurability bits, I should be able to play with the jupyter-server-proxy bits soon after that. If not, I can take a deeper look in a month or so once my current crunch of work has passed...

**Comment by choldgraf** [comment]
Woo!

**Comment by jakevdp** [comment]
Still TODO: update the example notebook and confirm it works on binder.

This may involve creating two copies of the notebook, one targeted to Colab (which only supports the non-proxied transformer) and one targeted to Binder (which only supports the proxied transformer).
