### ISSUE TITLE
Broken with Tornado 6.0

### ISSUE THREAD

**Issue by Corvince** [altair-viz/altair_data_server#4]
`tornado.wsgi.WSGIApplication` was removed in Tornado 6.0 ([source](https://github.com/tornadoweb/tornado/releases/tag/v6.0.0))

Used in [_provide.py](https://github.com/altair-viz/altair_data_server/blob/04952648baaa2f643d037d8c501873d978df69e2/altair_data_server/_provide.py#L134)

**Comment by jakevdp** [comment]
Thanks, will try to get a fix in soon.

**Comment by jakevdp** [comment]
In the meantime, I've adjusted the requirements: 0d8c94b

**Comment by camerondavison** [comment]
can you deploy a new pypi version for this fix? i just ran into this problem with `0.1.0`

**Comment by jakevdp** [comment]
@camerondavison I just released v0.2.0 to the Python package index:
```
$ pip install --upgrade altair_data_server
```
Let me know if this fixes your issue.
