### ISSUE TITLE
Provider with custom url (i.e. non-localhost)

### ISSUE THREAD

**Issue by cgbahk** [altair-viz/altair_data_server#48]
https://github.com/altair-viz/altair_data_server/blob/b0fdb38205877df7833481baa04b26ac6a9a245e/altair_data_server/_provide.py#L179-L181

It would be lovely if package user can set url if wanted.

As far as I inspected, there's no way to customize above `localhost` unless fixing inline, or using custom `Provider` (which is a bit hard for naive user)

## Issue use case
I use altair by displaying with `altair_viewer`
```py
chart = <some-altair-Chart>

chart.interactive().show()
```
This works great on local environment, where execution and view took place in same.

But sometimes, I hope to execute chart display code in remote environment, and want to view it in local browser, so execution and view took in different places. Accessing remote generate display IP (like `100.101.102.103:12345`) just shows white blank when accessed from local, guessing because main html content referring `localhost`, not `100.101.102.103`.

## Manual solution
I found fixing above `localhost` inline python code into my remote environment IP resolves the issue. But this feels like too manual. I hope there's official way to customize it.

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
