### ISSUE TITLE
compatibility with Altair 5.0.0RC1

### ISSUE THREAD

**Issue by samesand** [altair-viz/altair_data_server#49]
Is data_server compatible with 5.0.0RC1? I'm getting the following error after I upgraded Altair:
`
NoSuchEntryPoint: No 'data_server' entry point found in group 'altair.vegalite.v5.data_transformer'
` 

I tried 
`
from altair_data_server import data_server 
`
and I get no errors.

I'm using Python 3.11.2 and data server 0.4.1

Thank you.

**Comment by wieczyk** [comment]
Hi. What about this issue? If someone give me hints about internal I could program what is needed.

**Comment by ghost** [comment]
Facing the same issue.

**Comment by ghost** [comment]
OK. need to do this.
```
import altair as alt
from altair_data_server import data_server

alt.data_transformers.register("data_server", data_server)
alt.data_transformers.enable("data_server")

```

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
