### ISSUE TITLE
Add Colab-compatible notebook

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair_data_server#7]
The server proxy upgrade means that the current example notebook doesn't work in Colab. We should add two versions of the example notebook, one that works out-of-the-box in binder, and one that works out-of-the-box in colab.

**Comment by crepererum** [comment]
Did this ever work in colab? As far as I understand, there is not jupyter-server-proxy available for colab and I think they don't allow you to access random ports from the outside, or am I wrong?

**Comment by jakevdp** [comment]
Yes, this works in Colab with the ``data_server`` transformer, but not the ``data_server_proxied`` transformer.

**Comment by jakevdp** [comment]
Other differences between the examples:

- for Colab, package must be pip installed. For binder, it does not need to be
- in the proxied version (binder), pandas cannot access the data at the proxied URL. This needs to be removed from the demo. In the non-proxied version (colab), the resource is available at the given URL by both the backend and frontend.
