### ISSUE TITLE
Proxied version does not work for notebooks in subfolders

### ISSUE THREAD

**Issue by crepererum** [altair-viz/altair_data_server#8]
# Abstract
If using the `'data_server_proxied'` option and a notebook that is NOT at the root level (so in a sub-folder) the relative path to the proxy endpoint is wrong.

# Steps to Reproduce
1. Start binder from README link
2. Create sub-folder in jupyterlab sidebar and move example notebook there
3. Play through notebook and enable `'data_server_proxied'
4. Watch plots not loading

Side note: you can use your browser dev-tools (e.g. network monitor) to see 404s returned from the server.

# Technical reason
[Here](https://github.com/altair-viz/altair_data_server/blob/a873708a974423c9afb30636335575f0dec13ff3/altair_data_server/_altair_server.py#L56) we assume that the proxy is one level up from the notebook which is not current when the notebook is in a subfolder.

Sadly, using the opposite and assuming that the proxy is directly at the domain root is also wrong for solutions like binder (there you have a `user/<users>/lab` prefix).

What we would need is one of the two:
- the relative path of the current notebook to root
- the baseUrl (see [`jupyter-server-proxy` docs](https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports.html))

I don't currently know how to get any of these though :(

**Comment by jakevdp** [comment]
Thanks for the report – I can't think of any way to make this work, unfortunately.

**Comment by crepererum** [comment]
One potential idea is to get the base URL from `jupyter-server-proxy`, see https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#specifying-config-from-python-packages This however requires `altair_data_server` to be available on the jupyter server, not only within the kernel. Also it would require us to pass the base URL from the launched process server process to the kernel (e.g. via a tempfile). I have to admit that this sounds extremely hacky.

**Comment by ttimbers** [comment]
I am going to need to somehow find a way to make this work for a course we are developing... Do either of you know if the closed issues where this issue was referenced make any progress towards this? I am coming in a bit cold here, so if any direction forward could be given, I would be happy to try to pick up on this.

**Comment by ttimbers** [comment]
The PR in #47 solved this for me!

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
